[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:backend]
command=sh -c "npm run build && npm run migration:run && npm run start:debug"
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PORT=3004,NODE_ENV=development,NODE_PATH=/app/backend/src

[program:frontend]
command=sh -c "npm run setup && ./node_modules/.bin/remix build && ./node_modules/.bin/concurrently \"./node_modules/.bin/remix watch\" \"node --inspect=0.0.0.0:9230 --watch server.js\""
directory=/app/frontend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PORT=3000,NODE_ENV=development
